<a href="https://colab.research.google.com/github/mizuki-53/colab/blob/main/Python%E5%85%A5%E9%96%80%E3%83%8E%E3%83%83%E3%82%AF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# vol1
https://www.youtube.com/watch?v=Hd35Zq0efM8

In [ ]:
#文字列の代入
name='みずき'
birthplace='滋賀'

In [ ]:
'私は{}です。出身は{}です。'.format(name,birthplace)

'私はみずきです。出身は滋賀です。'

In [ ]:
f'私は{name}です。出身は{birthplace}です。'

'私はみずきです。出身は滋賀です。'

In [ ]:
#エスケープシーケンス
print('いつもの帰り道とは違うルートで帰ってみようかな。\n迷子にならないか心配だけど。')

いつもの帰り道とは違うルートで帰ってみようかな。
迷子にならないか心配だけど。


In [ ]:
#書式化
print("10進数=%d,16進数=%x,10進浮動小数点=%f"%(16,16,16))

10進数=16,16進数=10,10進浮動小数点=16.000000


In [ ]:
#大文字小文字への変換
'hELlo'.upper()

'HELLO'

In [ ]:
"HelLO".lower()

'hello'

In [ ]:
#文字列の分割
message="こんにちは。\n私はAIのロボットです。"
print(message)

こんにちは。
私はAIのロボットです。


In [ ]:
messages=message.split('\n')
messages

['こんにちは。', '私はAIのロボットです。']

In [ ]:
#文字列の結合
'〇〇'.join(messages)#〇〇の要素で結合する

'こんにちは。〇〇私はAIのロボットです。'

In [ ]:
#空白除去
message="　いつも食べるここのケーキはとても美味しいね。　"
print(message.strip())

いつも食べるここのケーキはとても美味しいね。


In [ ]:
#文字列の置換
message="今日は晴れですね"
message.replace('晴れ','雨')

'今日は雨ですね'

In [ ]:
#文字列検索
message="今日はとても夜空が綺麗だ。"
message.find('夜空')

6

In [ ]:
#型変換
x=1
str(x)

'1'

In [ ]:
x=1.52
str(x)

'1.52'

In [ ]:
x=[1,2,3]
str(x)

'[1, 2, 3]'

In [ ]:
x = dict(name='john',birth='US')
str(x)

"{'name': 'john', 'birth': 'US'}"

In [ ]:
#包含関係
a,b="sba",'gasba'

In [ ]:
a

'sba'

In [ ]:
b

'gasba'

In [ ]:
a in b

True

In [ ]:
b in a

False

In [ ]:
a,b="xdh",'orweit'

In [ ]:
a in b

False

In [ ]:
 #リスト
 #特定の値を抽出
 numbers=[0,3,8,-4,9,1]

In [ ]:
 numbers[1]

3

In [ ]:
 numbers[-1]

1

In [ ]:
numbers.append(2)
numbers

[0, 3, 8, -4, 9, 1, 2]

In [ ]:
#特定の値を挿入
numbers.insert(0,5)#０番目の前に5を挿入
numbers

[5, 0, 3, 8, -4, 9, 1, 2]

In [ ]:
numbers.insert(-1,-3)#最後の項目の前に-3を挿入
numbers

[5, 0, 3, 8, -4, 9, 1, -3, 2]

In [ ]:
#特定の値を削除
numbers.remove(5)#5を消す
numbers

[0, 3, 8, -4, 9, 1, -3, 2]

In [ ]:
numbers.remove(3)#3を消す
numbers

[0, 8, -4, 9, 1, -3, 2]

In [ ]:
numbers.pop(-3)#-3番目の要素を消す　＝1を消す
numbers

[0, 8, -4, 9, -3, 2]

In [ ]:
#フィルター
def isEven(number):
  if number % 2==0:
    print(f"This number ,{number} is even!")
    return True
  else:
    print(f'This number ,{number} is odd!')
    return False

In [ ]:
isEven(3)

This number ,3 is odd!


False

In [ ]:
#filter関数の使い方　filter(関数、リスト)
#filter関数で返ってくるのはインスタンスのみなので、リストとして使いたい場合は、list関数も使う
list(filter(isEven,numbers))

This number ,0 is even!
This number ,8 is even!
This number ,-4 is even!
This number ,9 is odd!
This number ,-3 is odd!
This number ,2 is even!


[0, 8, -4, 2]

In [ ]:
#引数と一致する要素のインデックス(要素番号の取得)
numbers.index(-4)

2

In [ ]:
#ソート
numbers.sort()
numbers

[-4, -3, 0, 2, 8, 9]

In [ ]:
numbers.sort(reverse=True)
numbers

[9, 8, 2, 0, -3, -4]

In [ ]:
#辞書
#要素の削除
dictionary={
    'A':'今西',
    'B':'航平',
    'C':'男性',
    'D':'東京都',
    'E':'海外旅行'
}
dictionary

{'A': '今西', 'B': '航平', 'C': '男性', 'D': '東京都', 'E': '海外旅行'}

In [ ]:
dictionary.pop('A')

'今西'

In [ ]:
dictionary

{'B': '航平', 'C': '男性', 'D': '東京都', 'E': '海外旅行'}

In [ ]:
dictionary.pop('B')

'航平'

In [ ]:
dictionary

{'C': '男性', 'D': '東京都', 'E': '海外旅行'}

In [ ]:
dictionary.clear()

In [1]:
dictionary

NameError: ignored

# Vol.2
https://www.youtube.com/watch?v=Oi_XXNZUUDg&t=33s

In [ ]:
#辞書
#情報の取得
dictionary={
    'A':'今西',
    'B':'航平',
    'C':'男性',
    'D':'東京都',
    'E':'海外旅行'
}
dictionary

{'A': '今西', 'B': '航平', 'C': '男性', 'D': '東京都', 'E': '海外旅行'}

In [ ]:
dictionary.keys() #キーのみを表示

dict_keys(['A', 'B', 'C', 'D', 'E'])

In [ ]:
"男性" in dictionary.values()#男性という値が存在するか判定

True

In [ ]:
#全てのキーと値の表示
#dictionary.items()
for key, value in dictionary.items():
  print(f'キーは{key},バリューは{value}')

キーはA,バリューは今西
キーはB,バリューは航平
キーはC,バリューは男性
キーはD,バリューは東京都
キーはE,バリューは海外旅行


In [ ]:
#辞書内の要素検索
dictionary={
    'A':'今西',
    'B':'航平',
    'C':'男性',
    'D':'東京都',
    'E':'海外旅行'
}
dictionary

{'A': '今西', 'B': '航平', 'C': '男性', 'D': '東京都', 'E': '海外旅行'}

In [ ]:
dictionary['E']

'海外旅行'

In [ ]:
#.get　のメソッドを使うと、辞書内にないキーを指定しても、エラーが出ない
dictionary.get('F')

In [ ]:
#制御構文(if文)
#if文を使って条件分岐

num = -3
if num > 0 :
  print('正の値です')
elif num == 0:
  print("0です")
else :
  print('負の値です')

負の値です


In [ ]:
#論理演算子を使って複数条件の指定
a= -4
if 0 <= a < 10 and a % 2 == 0 :
  print("一桁の偶数です")
elif a < 0 and a % 2 != 0 :
  print("負の奇数です")
else :
  print('整数です')

整数です


In [ ]:
#制御構文(for文)
#リストの要素を表示
names = ['John','Kevin' ,'Louis']
for name in names:
  print(name)

John
Kevin
Louis


In [ ]:
#range関数
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#27 強制終了
for i in range(10):
  if i == 6:
    print('終了!')
    break
  print(i)

0
1
2
3
4
5
終了!


In [ ]:
#28 ループの途中で特定の処理を実行
for i in range(10):
  if i == 3:
    continue
  print(i)

0
1
2
4
5
6
7
8
9


In [ ]:
#29 複数のリストを同時に処理→zip関数
lasts =['加藤','佐藤','田中']
firsts = ['雄一','拓哉','太郎']
for last,first in zip(lasts,firsts):
  print(last,first)

加藤 雄一
佐藤 拓哉
田中 太郎


In [ ]:
#30 要素と同時にインデックス情報の取得
lasts =['加藤','佐藤','田中']
for i,last in enumerate(lasts):
  print(f'{i}番の{last}です')

0番の加藤です
1番の佐藤です
2番の田中です


In [ ]:
#31内包表記
nums = []
for i in range(10):
  if i % 2 == 0:
    nums.append(i)

nums

[0, 2, 4, 6, 8]

In [ ]:
numbers = [2*i for i in range(5)]
numbers

[0, 2, 4, 6, 8]

In [ ]:
#例外処理
#32 0で割ったときの例外処理
num=0
try :
  print(f'計算結果：{10/num}')
except :
  print('エラー')

エラー


In [ ]:
#33 具体的なエラー内容の出力
num=0
try :
  print(f'計算結果：{10/num}')
except ZeroDivisionError as e:
  print(e)
#エラーの内容によって分岐ができる

division by zero


In [ ]:
#34 エラー内容ごとの例外処理
def divide(a,b):
  try:
    print(f'計算結果：{a/b}')
  except ZeroDivisionError as e:
    print(e)
  except TypeError as e:
    print(e)


In [ ]:
divide(1,'a')

unsupported operand type(s) for /: 'int' and 'str'


In [ ]:
#35 通常終了時に行う処理
def divide(a,b):
  try:
    print(f'計算結果：{a/b}')
  except ZeroDivisionError as e:
    print(e)
  except TypeError as e:
    print(e)
  else: #elseを付け加えると、正常終了時のコメント追加できる
    print('正常に終了しました')

In [ ]:
divide(1,7)

計算結果：0.14285714285714285
正常に終了しました


In [ ]:
#36 例外も含めた終了時に行う処理
def divide(a,b):
  try:
    print(f'計算結果：{a/b}')
  except ZeroDivisionError as e:
    print(e)
  except TypeError as e:
    print(e)
  finally: #finallyを付け加えると、正常orエラーにかかわらず終了時のコメント追加できる
    print('全ての処理が終了しました')

In [ ]:
divide(1,'a')

unsupported operand type(s) for /: 'int' and 'str'
全ての処理が終了しました


In [ ]:
#37　例外をスルー
def divide(a,b):
  try:
    print(f'計算結果：{a/b}')
  except ZeroDivisionError as e:
    print(e)
  except TypeError as e:
    pass #↑のエラー時の対応は何もしない,passをつけないと何かしらの命令を記載しないといけない
  finally: #finallyを付け加えると、正常orエラーにかかわらず終了時のコメント追加できる
    print('全ての処理が終了しました')

In [ ]:
divide(1,'a')

全ての処理が終了しました


クラスについて

In [ ]:
class Person:
  def __init__(self,name,nationality,age):#コンストラクタ　＝　初期化を担当する　初期設定
    self.name = name
    self.nationality = nationality
    self.age = age

  def __call__(self):
    print('ここはcallメソッドです。')

  def say_hello(self,name):#メソッドの定義、クラス内で定義されている関数をメソッド
    print(f'こんにちは{name}さん、私は{self.name}です。')#selfは呼び出したインスタンス自信を指す

In [ ]:
#インスタンス化（実体化）　設計書に沿った実態を作る
imanishi = Person('今西','日本',25)

In [ ]:
mike = Person('マイク','アメリカ',13) #マイクを実体化

In [ ]:
imanishi.name #属性を取り出す、クラス内で定義されている変数を属性という

'今西'

In [ ]:
imanishi.say_hello('酒井')

こんにちは酒井さん、私は今西です。


In [ ]:
mike.say_hello('酒井')

こんにちは酒井さん、私はマイクです。


In [ ]:
imanishi.__call__()

ここはcallメソッドです。


In [ ]:
imanishi() #コール関数は　インスタンス名() で呼び出せる

ここはcallメソッドです。


In [ ]:
#クラス
#38 classの基礎
class Person: #Personクラスを用意
  nationality = 'Japan'#クラス変数

  def say_hello(self):#クラスメソッド
    print(f'こんにちは、私の国籍は、{self.nationality}です。')

In [ ]:
person =Person()　#クラスのインスタンス化

In [ ]:
person.nationality

'Japan'

In [ ]:
person.say_hello()

こんにちは、私の国籍は、Japanです。


In [ ]:
#39 コンストラクタの設定
class Person: #Personクラスを用意
  nationality = 'Japan'#クラス変数

  def __init__(self,name):#コンストラクタ
    self.name = name

  def say_hello(self):#クラスメソッド
    print(f'こんにちは、私の国籍は、{self.nationality}です。')

  def say_my_name(self):
    print(f'私の名前は{self.name}です。')

In [ ]:
imanishi = Person('今西')

In [ ]:
imanishi.nationality

'Japan'

In [ ]:
imanishi.name

'今西'

In [ ]:
imanishi.say_my_name()

私の名前は今西です。


In [ ]:
#40　クラスの継承
class Kid(Person):#クラスを用意するときに、継承したいクラス名を指定する
  def say_hello(self,age):
    print(f'私の名前は{self.name}です。年齢は{age}歳です。')

In [ ]:
kid = Kid('けんすけ')

In [ ]:
kid.name

'けんすけ'

In [ ]:
kid.nationality

'Japan'

In [ ]:
kid.say_hello(12)

私の名前はけんすけです。年齢は12歳です。


In [ ]:
#41 private と　public
class Person:
  __nationality = 'Japan'#変数名の先頭に__をつけるだけでプライベートな変数に

  def __init__(self,name):
    self.name = name

  def say_hello(self):#クラスメソッド
    print(f'こんにちは、私の国籍は、{self.__nationality}です。')#プライベートな変数も、クラス内では呼びだせる

  def  __say_my_name(self):#メソッド名の先頭に__をつけるだけでプライベートなメソッドに
    print(f'私の名前は{self.name}です。')

In [ ]:
imanishi=Person('今西')

In [ ]:
imanishi.name

'今西'

In [ ]:
imanishi.__nationality

AttributeError: ignored

In [ ]:
imanishi.say_hello()

こんにちは、私の国籍は、Japanです。


In [ ]:
#58ベクトルの定義
import numpy as np
b = np.array([1,2,3,4])

In [ ]:
b

array([1, 2, 3, 4])

In [ ]:
b.shape

(4,)

In [ ]:
#61 加減乗算
A = np.array([[1,5],[4,-2]])
A

array([[ 1,  5],
       [ 4, -2]])

In [ ]:
B = np.array([[2,-1],[7,6]])
B

array([[ 2, -1],
       [ 7,  6]])

In [ ]:
A + B

array([[ 3,  4],
       [11,  4]])

In [ ]:
A - B

array([[-1,  6],
       [-3, -8]])

In [ ]:
 #行列積
 np.dot(A,B)

array([[ 37,  29],
       [ -6, -16]])